### ISSUE TITLE
Row padding/margin is lost

### ISSUE THREAD

**Issue by ermirbeqiraj** [Ecomailcz/bee-to-topol#5]
In some cases, row padding is lost

Original:
![image](https://user-images.githubusercontent.com/7790756/213183182-bb17f961-173b-4905-84d7-9b2f9efae0ff.png)

After conversion:
![image](https://user-images.githubusercontent.com/7790756/213183278-edf902a1-60e3-458f-aa77-06ef3f5017b4.png)

**Comment by tomsq** [comment]
fixed [here](https://github.com/Ecomailcz/bee-to-topol/commit/2c988625a4e78e58de9d24dd41af4878d5cc5aca)
